export interface LanguageOption { code: string; name: string; nativeName: string; }

// Common languages stay at the top; the full list is intentionally searched rather than exposed as a giant select.
const rows: Array<[string, string, string]> = [
  ["en", "English", "English"], ["ar", "Arabic", "Arabic"], ["es", "Spanish", "Spanish"], ["fr", "French", "French"], ["de", "German", "German"], ["pt", "Portuguese", "Portuguese"], ["it", "Italian", "Italian"], ["tr", "Turkish", "Turkish"], ["ru", "Russian", "Russian"], ["zh", "Chinese", "Chinese"], ["ja", "Japanese", "Japanese"], ["ko", "Korean", "Korean"],
  ["nl", "Dutch", "Dutch"], ["pl", "Polish", "Polish"], ["uk", "Ukrainian", "Ukrainian"], ["fa", "Persian", "Persian"], ["ur", "Urdu", "Urdu"], ["hi", "Hindi", "Hindi"], ["id", "Indonesian", "Indonesian"], ["vi", "Vietnamese", "Vietnamese"], ["he", "Hebrew", "Hebrew"], ["sv", "Swedish", "Swedish"], ["no", "Norwegian", "Norwegian"], ["da", "Danish", "Danish"],
  ["fi", "Finnish", "Finnish"], ["el", "Greek", "Greek"], ["cs", "Czech", "Czech"], ["ro", "Romanian", "Romanian"], ["hu", "Hungarian", "Hungarian"], ["th", "Thai", "Thai"], ["ms", "Malay", "Malay"], ["fil", "Filipino", "Filipino"], ["sw", "Swahili", "Swahili"], ["ta", "Tamil", "Tamil"], ["te", "Telugu", "Telugu"], ["bn", "Bengali", "Bengali"], ["gu", "Gujarati", "Gujarati"], ["kn", "Kannada", "Kannada"], ["ml", "Malayalam", "Malayalam"], ["mr", "Marathi", "Marathi"],
  ["pa", "Punjabi", "Punjabi"], ["ne", "Nepali", "Nepali"], ["si", "Sinhala", "Sinhala"], ["am", "Amharic", "Amharic"], ["af", "Afrikaans", "Afrikaans"], ["sq", "Albanian", "Albanian"], ["hy", "Armenian", "Armenian"], ["az", "Azerbaijani", "Azerbaijani"], ["eu", "Basque", "Basque"], ["be", "Belarusian", "Belarusian"], ["bs", "Bosnian", "Bosnian"], ["bg", "Bulgarian", "Bulgarian"], ["ca", "Catalan", "Catalan"], ["hr", "Croatian", "Croatian"], ["et", "Estonian", "Estonian"], ["gl", "Galician", "Galician"],
  ["ka", "Georgian", "Georgian"], ["is", "Icelandic", "Icelandic"], ["ga", "Irish", "Irish"], ["kk", "Kazakh", "Kazakh"], ["km", "Khmer", "Khmer"], ["lo", "Lao", "Lao"], ["lv", "Latvian", "Latvian"], ["lt", "Lithuanian", "Lithuanian"], ["mk", "Macedonian", "Macedonian"], ["mt", "Maltese", "Maltese"], ["mn", "Mongolian", "Mongolian"], ["sr", "Serbian", "Serbian"], ["sk", "Slovak", "Slovak"], ["sl", "Slovenian", "Slovenian"], ["so", "Somali", "Somali"], ["tg", "Tajik", "Tajik"],
  ["uz", "Uzbek", "Uzbek"], ["cy", "Welsh", "Welsh"], ["yi", "Yiddish", "Yiddish"], ["yo", "Yoruba", "Yoruba"], ["zu", "Zulu", "Zulu"], ["la", "Latin", "Latin"], ["eo", "Esperanto", "Esperanto"], ["ceb", "Cebuano", "Cebuano"], ["co", "Corsican", "Corsican"], ["fy", "Frisian", "Frisian"], ["gd", "Scottish Gaelic", "Scottish Gaelic"], ["ha", "Hausa", "Hausa"], ["haw", "Hawaiian", "Hawaiian"], ["ht", "Haitian Creole", "Haitian Creole"], ["hmn", "Hmong", "Hmong"], ["ig", "Igbo", "Igbo"],
  ["jw", "Javanese", "Javanese"], ["ku", "Kurdish", "Kurdish"], ["ky", "Kyrgyz", "Kyrgyz"], ["lb", "Luxembourgish", "Luxembourgish"], ["mi", "Maori", "Maori"], ["my", "Myanmar", "Myanmar"], ["ny", "Nyanja", "Nyanja"], ["ps", "Pashto", "Pashto"], ["sm", "Samoan", "Samoan"], ["sn", "Shona", "Shona"], ["su", "Sundanese", "Sundanese"], ["tk", "Turkmen", "Turkmen"], ["ug", "Uyghur", "Uyghur"], ["xh", "Xhosa", "Xhosa"], ["as", "Assamese", "Assamese"], ["ba", "Bashkir", "Bashkir"], ["br", "Breton", "Breton"], ["fo", "Faroese", "Faroese"],
  ["fr-CA", "French (Canada)", "French (Canada)"], ["en-GB", "English (United Kingdom)", "English (UK)"], ["en-US", "English (United States)", "English (US)"], ["es-419", "Spanish (Latin America)", "Spanish (Latin America)"], ["pt-BR", "Portuguese (Brazil)", "Portuguese (Brazil)"], ["zh-CN", "Chinese (Simplified)", "Chinese (Simplified)"], ["zh-TW", "Chinese (Traditional)", "Chinese (Traditional)"], ["ar-EG", "Arabic (Egypt)", "Arabic (Egypt)"], ["de-DE", "German (Germany)", "German (Germany)"], ["it-IT", "Italian (Italy)", "Italian (Italy)"], ["ja-JP", "Japanese (Japan)", "Japanese (Japan)"], ["ko-KR", "Korean (Korea)", "Korean (Korea)"], ["ru-RU", "Russian (Russia)", "Russian (Russia)"],
];

export const LANGUAGE_OPTIONS: LanguageOption[] = rows.map(([code, name, nativeName]) => ({ code, name, nativeName }));
export const LANGUAGE_OPTION_MAP = new Map(LANGUAGE_OPTIONS.map((option) => [option.code, option]));
